#!/usr/bin/env python
import argparse
import logging
import names
import pathlib
import random
import re

from signup_genius import get_signups_from_html

COMMENTS = ['A comment', 'Another comment', 'Interesting comment', 'Just picking daisies', 'Nothing to see here']


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('files', nargs='+')
    parser.add_argument(
        '-q', '--quiet', help="Only warnings or errors",
        action="store_const", dest="loglevel", const=logging.WARNING, default=logging.INFO,
    )
    parser.add_argument(
        '-v', '--verbose', help="Be verbose", action="store_const", dest="loglevel", const=logging.DEBUG
    )
    return parser.parse_args()


def main():
    args = parse_args()
    logging.basicConfig(level=args.loglevel)
    for file in args.files:
        path = pathlib.Path(file).resolve()
        html = path.read_text()
        for signup in get_signups_from_html(html):
            html = html.replace(signup.name, names.get_full_name())
    html = re.sub(r'<div class="SUGMemberComment">.*?</div>', random_comment_div, html)
    html = re.sub(r'<span class="SUGsmall">.*?</span>', random_comment_span, html)
    print(html)


def random_comment_div(match):
    return f'<div class="SUGMemberComment">{random.choice(COMMENTS)}</div>'


def random_comment_span(match):
    return f'<span class="SUGsmall">{random.choice(COMMENTS)}</span>'


if __name__ == '__main__':
    raise SystemExit(main())
